import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout/Layout'
import { useAccount, useProvider, useSigner } from 'wagmi'
import { TableContainer ,Table ,TableCaption ,Thead ,Tr ,Th,Tbody,Td,Tfoot,SimpleGrid,CardFooter,VStack,InputLeftElement,show,FormLabel,InputGroup,inputEl,InputRightElement,loading     ,Select,NumberInput ,NumberInputField ,NumberInputStepper ,NumberIncrementStepper ,NumberDecrementStepper ,Center,RadioGroup ,Radio,useColorMode ,Button,Box,Spacer,Grid,HStack,Flex,Text,GridItem,LinkBox,Heading,LinkOverlay,Stat,StatGroup,StatLabel,StatNumber,StatHelpText,StatArrow,Card,CardHeader,CardBody,Stack,StackDivider } from '@chakra-ui/react'
import { Alert, AlertIcon, AlertTitle, AlertDescription,} from '@chakra-ui/react'
import { Input } from '@chakra-ui/react'
import { ConnectButton } from '@rainbow-me/rainbowkit';
import "@fontsource/cinzel-decorative"
import "@fontsource/archivo-black"
import { CheckIcon, CloseIcon } from '@chakra-ui/icons'


import React, { useEffect, useState } from 'react';
import { loadDefaultErrorComponents } from 'next/dist/server/load-components'

export default function Home() {

  const { address, isConnected } = useAccount()
  const { colorMode, toggleColorMode } = useColorMode()
  const [winningAmoutMessage, setWinningAmount] = useState("1 x 1,97 = 1,97");
  const handleWinningAmountChange  = (event) => {
    setWinningAmount(event.target.value);
  };



  return (
    <>
      <Head>
        <title>Shifumi DApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Grid 
        h='100%'
        width='100%'
        p="1rem"
        templateRows='repeat(1, 1fr)'
        templateColumns='repeat(5, 1fr)'
        gap={3}
      >
        <GridItem rowSpan={2} colSpan={1}  >
        
          <Card alignItems="top"> 
          <Flex width="80%" justifyContent="space-between" alignItems="center">
                <Image width="1000" height="200" src='/logo.png' alt='Shifumi' />
               
            </Flex>

            <CardBody>
              <Stack divider={<StackDivider />} spacing='4'>
                <Box>
                <Heading size='md' textTransform='uppercase' fontFamily="alice">
                    Games
                  </Heading>
                  <br></br>
                  <Text pt='1' fontSize='sm' fontFamily="alice">
                    Shifumi
                  </Text>
                </Box>
                <Box>
                  <Text pt='1' fontSize='sm' fontFamily="alice">
                    Coin Flip
                  </Text>
                </Box>
                <Box>
                  <Text pt='1' fontSize='sm' fontFamily="alice">
                    Roulette
                  </Text>
                </Box>
                
              </Stack>
            </CardBody>
            </Card>
          <br></br>
          <Card alignItems="top">
            <CardBody >
              <Stack divider={<StackDivider />} spacing='4'>
                <Box>
                <Heading size='md' textTransform='uppercase' fontFamily="alice">
                    Protocol
                  </Heading>
                  <br></br>
                  <Text pt='1' fontSize='sm' fontFamily="alice">
                    Leadbord
                  </Text>
                </Box>
                <Box>
                  <Text pt='1' fontSize='sm' fontFamily="alice">
                    Stats
                  </Text>
                </Box>
              </Stack>
            </CardBody>
          </Card>
          <br></br>
          <Button onClick={toggleColorMode}>
        Toggle {colorMode === 'light' ? 'Dark' : 'Light'}
      </Button>
        </GridItem>

      <GridItem colSpan={4} >

      <Grid 
        width='100%'
        
        templateRows='repeat(1, 1fr)'
        templateColumns='repeat(4, 1fr)'
        gap={3}
      >
        <GridItem rowSpan={1} colSpan={4}  >
          <Card>
            <CardBody>
              
              
          <Grid templateColumns='repeat(5, 1fr)' gap={4}>
        <GridItem colSpan={2} >
          {isConnected ? (
            <Text>Your Shifhumi balance :</Text>
          ) : (
            <Text></Text>
          )}
        </GridItem>
         <GridItem colStart={6} colEnd={6} align="right">
          <ConnectButton />
         </GridItem>
          </Grid>
            </CardBody>
          </Card>
        </GridItem>
        </Grid>
          <br></br>
      <Grid 
        width='100%'
        
        templateRows='repeat(1, 1fr)'
        templateColumns='repeat(4, 1fr)'
        gap={3}
      >
        <GridItem rowSpan={1} colSpan={1}  >
          <Card>
            <CardBody>
              <HStack spacing='24px'>
                <Box >
                  <Image
                    borderRadius='full'
                    boxSize='64px'
                    src='/somme.png'
                    alt='Dan Abramov'
                    width="64"
                    height="64"
                  />
                </Box>
                <Box >
                  <Stat>
                    <StatLabel color="#aab4d3" fontFamily="alice">Bankroll</StatLabel>
                    <StatNumber  fontFamily="alice">345,670$</StatNumber>
                    <StatHelpText  fontFamily="alice">
                    <StatArrow type='increase' />3.36%</StatHelpText>
                  </Stat>
                </Box>
              </HStack>
            </CardBody>
          </Card>
        </GridItem>
        <GridItem rowSpan={1} colSpan={1}  >
          <Card>
            <CardBody>
              <HStack spacing='24px'>
                <Box >
                  <Image
                    borderRadius='full'
                    boxSize='64px'
                    src='/players.png'
                    alt='Dan Abramov'
                    width="64"
                    height="64"
                  />
                </Box>
                <Box >
                  <Stat>
                    <StatLabel color="#aab4d3"  fontFamily="alice">Players</StatLabel>
                    <StatNumber  fontFamily="alice">105</StatNumber>
                    <StatHelpText  fontFamily="alice">
                    <StatArrow type='decrease' />1.05%</StatHelpText>
                  </Stat>
                </Box>
              </HStack>
            </CardBody>
          </Card>
        </GridItem>
        <GridItem rowSpan={1} colSpan={1}  >
          <Card>
            <CardBody>
              <HStack spacing='24px'>
                <Box >
                  <Image
                    borderRadius='full'
                    boxSize='64px'
                    src='/played.png'
                    alt='Dan Abramov'
                    width="64"
                    height="64"
                  />
                </Box>
                <Box >
                  <Stat>
                    <StatLabel color="#aab4d3" font="alice">Games Played</StatLabel>
                    <StatNumber  fontFamily="alice">2390</StatNumber>
                    <StatHelpText  fontFamily="alice">
                    <StatArrow type='increase' />6.84%</StatHelpText>
                  </Stat>
                </Box>
              </HStack>
            </CardBody>
          </Card>
        </GridItem>
        <GridItem rowSpan={1} colSpan={1}  >
          <Card>
            <CardBody>
              <HStack spacing='24px'>
                <Box >
                  <Image
                    borderRadius='full'
                    boxSize='64px'
                    src='/fees.png'
                    alt='Dan Abramov'
                    width="64"
                    height="64"
                  />
                </Box>
                <Box >
                  <Stat>
                    <StatLabel color="#aab4d3"  fontFamily="alice">Fees</StatLabel>
                    <StatNumber  fontFamily="alice">721$</StatNumber>
                    <StatHelpText  fontFamily="alice">
                    <StatArrow type='increase' />2.55%</StatHelpText>
                  </Stat>
                </Box>
              </HStack>
            </CardBody>
          </Card>
        </GridItem>
        </Grid>

          <br></br>
          <Grid 
        width='100%'
        
        templateRows='repeat(1, 1fr)'
        templateColumns='repeat(4, 1fr)'
        gap={3}
      >
         <GridItem rowSpan={1} colSpan={3} >
         <Card height="100%">
            <CardBody>
              <Stack divider={<StackDivider />} spacing='4'>
                <Box>
                <Heading size='md' textTransform='uppercase' fontFamily="alice"> 
                    Coin Flip
                  </Heading>
                  <br></br>
                </Box>
              
                <VStack
                  spacing={2}
                  align='stretch'
                >
                  
                  <Box>
                    <Center>
                      <Text fontSize="50" fontFamily="Archivo Black">X 1,97</Text>
                    </Center>
                  </Box>
                  <Box>
                    <Center>
                      <Image width="128" height="128" src='/heads.png' alt='Shifumi' />
                    </Center>
                  </Box>
                  <Box>
                    <Center>                  
                      <Input width="30%" placeholder='Amount' type='number' align="center" onChange={handleWinningAmountChange}/>
                    </Center> 
                  </Box>
                  <Box>
                    <Center>
                      <SimpleGrid fontSize="13" w="30%" columns={2} spacing={1}>
                      <Box>Payout: 3</Box>
                      <Box align="right" >3% fees = 0.03</Box>
                      <Box >Bankroll:  30994</Box>
                      <Box align="right">Max payout: 2000</Box>
                      </SimpleGrid>
                    </Center> 
                  </Box>
                  <Box>
                    <Center>
                    {isConnected ? (
                    <Button width="30%" colorScheme='red'>Heads to win matic</Button>
                  ) : (
                    <Button width="30%" colorScheme='red'>Please connect your wallet</Button>
                  )}
                      
                    </Center> 
                  </Box>
                </VStack>
              </Stack>
            </CardBody>
          </Card>

         </GridItem>
         <GridItem rowSpan={1} colSpan={1} >
         <Card height="100%" >
            <CardBody>
              <Stack divider={<StackDivider />} spacing='4'>
                <Box>
                <Heading size='md' textTransform='uppercase' fontFamily="alice"> 
                    BET COINS
                  </Heading>
                  <br></br>
                </Box>

                <TableContainer>
  <Table variant='simple'>
    <TableCaption>Select your coin</TableCaption>
    <Thead>
      <Tr>
        <Th></Th>
        <Th>Coins</Th>
        <Th isNumeric>Your balance</Th>
      </Tr>
    </Thead>
    <Tbody>
      <Tr height="5px">
        <Td><Image width="48" height="48" src='/matic_balance.png' alt='Shifumi' /></Td>
        <Td>MATIC</Td>
        <Td isNumeric>25.4</Td>
      </Tr>
      <Tr>
        <Td><Image width="48" height="48" src='/ethereum_balance.png' alt='Shifumi' /></Td>
        <Td>ETH</Td>
        <Td isNumeric>30.48</Td>
      </Tr>
      <Tr>
        <Td><Image width="48" height="48" src='/usdc_balance.png' alt='Shifumi' /></Td>
        <Td>USDC</Td>
        <Td isNumeric>307.12</Td>
      </Tr>
    </Tbody>
  </Table>
</TableContainer>
                
              </Stack>
            </CardBody>
          </Card>

         </GridItem>
      </Grid>
          
          <br></br>
          <Card >
            <CardBody>
              <Stack divider={<StackDivider />} spacing='4'>
                <Box>
                <Heading size='md' textTransform='uppercase' fontFamily="alice"> 
                    Results
                  </Heading>
                  <br></br>
                </Box>
                <Center color='black'>
                <TableContainer width="100%">
  <Table variant='simple' >
    <Thead>
      <Tr>
        <Th></Th>
        <Th>Games</Th>
        <Th isNumeric>Bet</Th>
        <Th isNumeric>Multiplier</Th>
        <Th>Choice</Th>
        <Th>Result</Th>
        <Th isNumeric>Payout</Th>
        <Th>Coins</Th>
        <Th isNumeric>Protocol fees</Th>
        <Th>Date</Th>
      </Tr>
    </Thead>
    <Tbody>
      <Tr>
        <Td><CheckIcon color="green" /></Td>
        <Td>Flip</Td>
        <Td isNumeric>2</Td>
        <Td isNumeric>1.97</Td>
        <Td>Heads</Td>
        <Td>Heads</Td>
        <Td isNumeric>3.94</Td>
        <Td><Image width="36" height="36" src='/matic_balance.png' alt='Shifumi' /></Td>
        <Td isNumeric>0.06</Td>
        <Td>2023-03-29 11:47:00</Td>
      </Tr>
      <Tr>
        <Td><CloseIcon color="red" /></Td>
        <Td>Flip</Td>
        <Td isNumeric>2</Td>
        <Td isNumeric>1.97</Td>
        <Td>Heads</Td>
        <Td>Heads</Td>
        <Td isNumeric>0</Td>
        <Td><Image width="36" height="36" src='/matic_balance.png' alt='Shifumi' /></Td>
        <Td isNumeric>0.06</Td>
        <Td>2023-03-29 11:47:00</Td>
      </Tr>
      <Tr>
        <Td><CheckIcon color="green" /></Td>
        <Td>Flip</Td>
        <Td isNumeric>2</Td>
        <Td isNumeric>1.97</Td>
        <Td>Heads</Td>
        <Td>Heads</Td>
        <Td isNumeric>3.94</Td>
        <Td><Image width="36" height="36" src='/matic_balance.png' alt='Shifumi' /></Td>
        <Td isNumeric>0.06</Td>
        <Td>2023-03-29 11:47:00</Td>
      </Tr>
    </Tbody>
    <Tfoot>
      <Tr>
        <Th></Th>
        <Th>Games</Th>
        <Th isNumeric>Bet</Th>
        <Th isNumeric>Multiplier</Th>
        <Th>Choice</Th>
        <Th>Result</Th>
        <Th isNumeric>Payout</Th>
        <Th>Coins</Th>
        <Th isNumeric>Protocol fees</Th>
        <Th>Date</Th>
      </Tr>
    </Tfoot>
  </Table>
</TableContainer>
                </Center>
              </Stack>
            </CardBody>
          </Card>

        </GridItem>
      </Grid>
      </Layout>
    </>
  )
}